AQWAS/AqwasAPI/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using AqwasAPI.Areas.HelpPage.ModelDescriptions;
using AqwasAPI.Areas.HelpPage.Models;

namespace AqwasAPI.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

AQWAS/AqwasAPI/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.ServiceModel.Syndication;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace AqwasAPI.Controllers
{
    public class DefaultController : BaseController
    {
        // GET: Default
        public ActionResult Index()
        {
            ViewBag.Catogery = DAL.AqwasDAL.GetCategoryListForDropdownlist();
            return View();
        }
        [HttpPost]
        public JsonResult GetRSSLinks(int? CatogeryID, int? NewsPaperID)
        {
            try
            {
                var _data = DAL.AqwasDAL.GetLinksListForDropdownlist(CatogeryID, NewsPaperID);
                return Json(new { data = _data, Message = "success" });
            }
            catch (Exception)
            {
                return Json(new { data = "", Message = "Error" });
            }

        }
        public ActionResult SaveRSS(string FeedID, string Link)
        {
            var res = DAL.AqwasDAL.InsertRSSNewsInDB(FeedID, Link);
            if (res == "-1")
            {
                return Json(new { data = res, Message = Resources.Aqwas.userval4 });
            }
            else if (res == "0")
            {
                return Json(new { data = res, Message = Resources.Aqwas.ErrorMsg });
            }
            return Json(new { data = res, Message = Resources.Aqwas.SuccessMsg });
        }
     
        public ActionResult Error()
        {
            return View();
        }
    }
}

AQWAS/AqwasAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - @Resources.Aqwas.ProjectTitle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <!--BEGIN LOADER -->
    <div class="blockUI quick-nav-overlay" style="display: none;" id="loader-overlay">
        <div class="blockUI blockOverlay" style="z-index: 1100; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgba(0,0,0,0.9); opacity: 0.20; cursor: wait; position: fixed;"></div>
        <div class="blockUI blockMsg blockPage" style="z-index: 1101; display: block; position: fixed; padding: 0px; margin: 0px; top: 45%; left: 45%; text-align: center; color: rgb(0,0,0); border: 0px none; cursor: wait;">
            <div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
        </div>
    </div>
    <!-- END LOADER -->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.Aqwas.AqwasManagment, "Index", "Default", new { area = "" }, new { @class = "navbar-brand " })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Aqwas.Home, "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Resources.Aqwas.ProjectTitle</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

AQWAS/AqwasAPI/Views/Shared/_WebLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicons -->
    <link rel="shortcut icon" href="~/favicon.ico" />

    <!-- CSS -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/vendor/slick/slick.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />

    <!-- JS - MEDIAQUERIES -->
    <script src="~/Scripts/css3-mediaqueries.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @RenderSection("head", required: false)
</head>
<body>
    <!--BEGIN LOADER -->
    <div class="blockUI quick-nav-overlay" style="display: none;" id="loader-overlay">
        <div class="blockUI blockOverlay" style="z-index: 1100; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgba(0,0,0,0.9); opacity: 0.20; cursor: wait; position: fixed;"></div>
        <div class="blockUI blockMsg blockPage" style="z-index: 1101; display: block; position: fixed; padding: 0px; margin: 0px; top: 45%; left: 45%; text-align: center; color: rgb(0,0,0); border: 0px none; cursor: wait;">
            <div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
        </div>
    </div>
    <!-- END LOADER -->
    <input type="hidden" id="hd_lang" value="@Resources.Aqwas.Lang" />
    <!-- Topbar -->
    <div class="top-bar container">
        <div class="row">
            <div class="col-md-6">
                <ul class="tb-left">
                    <li class="tbl-date">@Resources.Aqwas.Todayis <span>@DateTime.Now.ToLongDateString()</span></li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="tb-right">
                    <li class="tbr-social">
                        <span>
                            @{
                                // If User Login
                                if (ViewBag.UserID != null && ViewBag.UserID.ToString() != "")
                                {
                                    <a href="javascript:void(0);">@Resources.Aqwas.Welcome  @ViewBag.UEmail</a>
                                    <a href="/Home/logout">
                                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                                        @Resources.Aqwas.Logout
                                    </a>
                                }
                                else
                                {
                                    // If User Not Login
                                    <a href="/Home/Login">@Resources.Aqwas.Login</a>
                                }
                            }
                        </span>
                    </li>
                    <li class="tbr-login">
                        <a href="javascript:void(0);" class="changelang">@Resources.Aqwas.language</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="container wrapper">
        <!-- Header -->
        <header>
            <div class="col-md-12">
                <div class="row">
                    <!-- Navigation -->
                    <div class="col-md-12">
                        <div class="menu-trigger"><i class="fa fa-align-justify"></i> Menu</div>
                        <nav>
                            <ul>
                                @{
                                    var _catobj = DAL.AqwasDAL.BindCatogery().ToList();// Get All Catogery
                                    if (_catobj != null && _catobj.Count() > 0)
                                    {
                                        foreach (var item in _catobj)
                                        {
                                            <li><a href="/Home/CatogryNews?Id=@item.id">@item.Name</a></li>
                                        }
                                    }
                                }
                            </ul>
                        </nav>

                        <!-- Search -->
                        <div class="search">
                            <form>
                                <input type="search" placeholder="Type to search and hit enter" />
                            </form>
                        </div>
                        <span class="search-trigger"><i class="fa fa-search"></i></span>
                    </div>
                </div>
            </div>
        </header>

        <div class="header">
            <div class="col-md-12">
                <div class="col-md-12">
                    <!-- Logo -->
                    <div class="col-md-4 logo">
                        <div class="clearfix space20"></div>
                        <a href="javascript:void(0);"><img src="https://aqwas.sa//static/media/aqwasLogo.e7919109.svg" alt="aqwas logo"></a>
                        <div class="clearfix space20"></div>
                    </div>
                    <!-- News Ticker -->
                    <div class="col-md-8">
                        @*<div class="news-ticker">
                                <div id="news-ticker">
                                    <div class="item">
                                        <span>Entertainment</span>
                                        <h4><a href="single_post.html">Movie : Mother - Real Beauty Comes from the Inside of a Woman</a></h4>
                                        <p>Posted on : November 4, 2017</p>
                                    </div>
                                    <div class="item">
                                        <span>Sport</span>
                                        <h4><a href="single_post.html">Temper Cum Soluta Nobis Eleifend Option Congue Nihil</a></h4>
                                        <p>Posted on : November 2, 2017</p>
                                    </div>
                                    <div class="item">
                                        <span>Business</span>
                                        <h4><a href="single_post.html">Duis autem vel irure dolor in hendrerit in vulputate</a></h4>
                                        <p>Posted on : November 1, 2017</p>
                                    </div>
                                </div>
                            </div>*@
                    </div>
                </div>
            </div>
        </div>
        <!--End Header -->
        <!-- Main Content -->
        <div class="main-content container">
            @RenderBody()
        </div>

        <!-- Footer - Fixed -->
        <div class="footer-fixed">
            <div class="row">
                <div class="col-md-6"></div>
                <div class="col-md-6">
                    <p class="copy1">@Resources.Aqwas.Copyright &copy; @Resources.Aqwas.ProjectTitle </p>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix space20"></div>
    <!-- Javascript -->
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/vendor/slick/slick.js"></script>
    <script src="~/Scripts/jquery.nicescroll.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/General.js"></script>
</body>
</html>